services:
    erfans.maintenance.maintenance_listener:
        class: Erfans\MaintenanceBundle\EventListener\MaintenanceListener
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@router"
            - "@erfans.maintenance.maintenance"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    erfans.maintenance.maintenance:
        class: Erfans\MaintenanceBundle\Maintenance\Maintenance
        public: false
        arguments:
            - "@router"
